### PR TITLE
UPDATE dependencies, ADD drag handles

### PR DESCRIPTION
**Pull request by haraldox**
@bokuweb FIXED some warnings and errors
ADD dragHandleClass (replaces #30)

### CODE REVIEW

**Comment by bokuweb** [comment]
Why remove react from (peer/dev)dependencies?

**Comment by haraldox** [comment]
causes error: multiple copies of React, see: https://gist.github.com/jimfb/4faa6cbfb1ef476bd105

if you do a clean npm install you will notice the error as well probably...

is react as a dependency really necessary? peer should be fine though

**Comment by bokuweb** [comment]
Please add `react` to `devdependencies` for test and example.

**Comment by IanVS** [comment]
I have problems with that error when I try to `npm link` this package into my project.  It would be very nice not to have react as a dependency, especially if it is not really needed.

**Comment by bokuweb** [comment]
@IanVS hm, If you want to use `npm link`, it might be to remove dependency.

**Pull request closed without merging**
