### PR TITLE
Split SortablePane component into smaller files 

### PR DESCRIPTION
**Pull request by haraldox**
in order to make it easier to comprehend

### CODE REVIEW

**Comment by haraldox** [comment]
hi @bokuweb! thanks for continuously updating `react-sortable-pane`! 👍 

may I ask you for some feedback on this pull request? splitting your code into smaller files helps debugging tremendously and makes understanding your codebase much simpler...

thanks a million!

**Comment by bokuweb** [comment]
@haraldox I'm sorry I'm so late.
- Should react-resizable-box download from npm
- It looks too fragmented for me, object.assign is not required to combine fragment.
  - Distinction to keep the particle size of the components

**Comment by haraldox** [comment]
i think it's more elegant to use more, smaller files than one large file.

i spent hours hunting down a bug, and it's much easier now that the code is split

**Comment by bokuweb** [comment]
Ummmm, I know, but this looks an excess of as .

**Comment by haraldox** [comment]
@bokuweb too bad, it made the code so much cleaner and easier to understand :(

do you know of any other methods to split class members across files instead of `Object.assign`?

I got inspired from: http://stackoverflow.com/questions/27956779/splitting-up-class-definition-in-es-6-harmony

**Comment by bokuweb** [comment]
High order component
https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775

But, I think, there is no need to separate any more

**Pull request closed without merging**
