### PR TITLE
Fixes #227 issue where onDragStop is fired on mouse move over pane

### LINKED ISSUE #227: onDragStop fires on mousemove over panes
### Overview of the problem

I'm using **version** 1.0.2
My **browser** is Google Chrome

### Description

The `onDragStop` callback function is fired every time the mouse moves over a pane rather than just when the mouse is released.

### Steps to Reproduce

* Create simple list of panes - e.g., https://codesandbox.io/s/0o4x4mx3xv
* Add onDragStop prop
* Move mouse over the panes. onDragStop function is called.

### Expected behavior

onDragStop to only be called when mouse is released after dragging panes.

### Actual behavior

onDragStop is fired on mouse move.

### PR DESCRIPTION
**Pull request by PabloDiablo**
### Proposed solution
Fixes issue #227 by adding check for `isPressed` before calling `onDragStop`. Also adds pane order as a new parameter to `onDragStop`.

### Tradeoffs
N/A

### Testing Done
Tested locally.

### CODE REVIEW

**Comment by bokuweb** [comment]
@PabloDiablo Thanks 👍

**Comment by bokuweb** [comment]
@PabloDiablo 1.0.3 published 🎉  Could you please try this version if you have time :)

**Comment by PabloDiablo** [comment]
@bokuweb thanks for the quick turnaround! I've upgraded in NPM to 1.0.3. I can see the updated README but the built code and types are still from 1.0.2. Can you check it built correctly before it was published?

**Comment by bokuweb** [comment]
@PabloDiablo Ooooooooooooops 😢 Sorry, I updated. Could you please try v1.0.4 🙏

**Comment by PabloDiablo** [comment]
Tested and working! Thanks ✋

**Pull request merged**
